name: users_data_source
description: A generic interface for managing users.
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1
  mysql1: ^0.20.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
